# fly.toml app configuration file generated for linear-chain-trick on 2025-10-04T20:25:28-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'linear-chain-trick'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 15
    soft_limit = 10

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
